version: '3'

services:
  db:
    container_name: nextcloud_db
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD

  redis:
    container_name: nextcloud_redis
    image: redis:alpine
    restart: always

  app:
    container_name: nextcloud_app
    image: nextcloud:fpm-alpine
    restart: always
    volumes:
      - ./data/html:/var/www/html
    environment:
      - MYSQL_HOST=db
      - REDIS_HOST=redis
    depends_on:
      - db
      - redis

  web:
    container_name: nextcloud_web
    build: ./web
    restart: always
    volumes:
      - ./data/html:/var/www/html:ro
    environment:
      - VIRTUAL_HOST
      - LETSENCRYPT_HOST=${VIRTUAL_HOST}
    depends_on:
      - app
    networks:
      default:
      nginx-proxy:
        aliases:
          - ${VIRTUAL_HOST}
  
  cron:
    container_name: nextcloud_cron
    image: nextcloud:fpm-alpine
    restart: always
    volumes:
      - ./data/html:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis

volumes:
  db:
  nextcloud:

networks:
  nginx-proxy:
    external: true
